sys-apps/kexec-tools: remove mcmodel option from CFLAGS
To be able to build kexec-tools with CFLAGS that would protect against
Spectre v2, we need to remove the option `-mcmodel=large`. Otherwise
build will fail like this:

```
purgatory/purgatory.c:13:1: error: ‘-mindirect-branch=thunk’ and
‘-mcmodel=large’ are not compatible
```